export default {
  "bar-pnt-01" : {
    "fresh" : 1,
    "musky" : 2,
    "woodsy" : 3, 
    "little" : 1,
    "lot" : 3,
    "camping" : 1, 
    "exploring" : 2,
    "hiking" : 3, 
    "beer" : 2, 
    "bourbon" : 3,
    "tequila" : 1,
  },
  "bar-gpf-01" : {
    "fresh" : 1,
    "sweet" : 3,
    "none" : 3,
    "sailing" : 2, 
    "exploring" : 1,
    "relaxing" : 3,
    "beer" : 3, 
    "tequila" : 2,
    "champagne" : 1,
  },
  "bar-gms-01" : {
    "musky" : 3,
     "herbal" : 1,
     "woodsy" : 2,
     "none" : 3,
     "sailing" : 1,
     "exploring" : 3,
     "hiking" : 2,
     "beer" : 1,
     "bourbon" : 3,
     "rum" : 2,
  },
  "bar-alp-01" : {
    "fresh" : 2, 
    "musky" : 1,
    "herbal" : 3,
    "none" : 3,
    "sailing" : 3,
    "exploring" : 2,
    "relaxing" : 1,
    "beer" : 1,
    "champagne" : 3,
    "rum" : 2, 
  },
  "bar-brm-01" : {
    "musky" : 3,
    "herbal" : 2, 
    "sweet" : 1,
    "none" : 3,
    "sailing" : 2,
    "relaxing" : 3,
    "hiking" : 1,
    "beer" : 1,
    "bourbon" : 2,
    "rum" : 3, 
  },
  "bar-cdc-01" : {
    "fresh" : 1, 
    "woodsy" : 3, 
    "sweet" : 2,
    "little" : 3,
    "lot" : 2,
    "exploring" : 2,
    "relaxing" : 1,
    "hiking" : 3,
    "beer" : 1,
    "bourbon" : 3, 
    "champagne" : 2, 
  },
  "bar-sbs-01" : {
    "fresh" : 3,
    "herbal" : 2, 
    "woodsy" : 1,
    "none" : 3,
    "sailing" : 2,
    "exploring" : 1,
    "hiking" : 3,
    "beer" : 1,
    "tequila" : 3,
    "champagne" : 2,
  },
  "bar-egy-01" : {
    "fresh" : 2,
    "herbal" : 3,
    "woodsy" : 1,
    "little" : 3,
    "lot" : 2,
    "camping" : 3,
    "exploring" : 2,
    "relaxing" : 1,
    "tequila" : 2,
    "champagne" : 3,
    "rum" : 1
  },
  "bar-cfa-01" : {
    "fresh" : 3,
    "herbal" : 2,
    "sweet" : 1,
    "none" : 3,
    "camping" : 3,
    "sailing" : 1,
    "relazing" : 2, 
    "tequila" : 3,
    "champagne" : 2,
    "rum" : 1,
  },
  "bar-dsg-01" : {
    "fresh" : 3,
    "musky" : 1,
    "herbal" : 2,
    "little" : 3,
    "lot" : 2,
    "sailing" : 3, 
    "relaxing" : 2,
    "hiking" : 1,
    "beer" : 2,
    "champagne" : 1,
    "rum" : 3
  },
  "bar-cof-01" : {
    "musky" : 1,
    "woodsy" : 2,
    "sweet" : 3,
    "little" : 2,
    "lot" : 3,
    "camping" : 3,
    "exploring" : 2,
    "hiking" : 1,
    "beer" : 2,
    "bourbon" : 3,
    "rum" : 1
  },
  "hair-kit-1" : {
    "long" : 3,
    "medium" : 3,
    "short" : 3
  },
  "soap-gripper" : {
    "bald" : 3
  }
};